klient/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	
    #url(r'^$', views.realestate_start, name='startre'),
	#url(r'^cennik/$', views.cennik, name='cennik'),
	#url(r'^regulamin/$', views.regulamin, name='regulamin'),
	#url(r'^edfi/$', views.edit_firm, name='editfirm'),
	#url(r'^pitka/$', views.probino, name='probino'),
	url(r'^fspr/$', views.firma_sprawdzana, name='sprfirma'),
	url(r'^fspr/(?P<nip>[0-9]+)/$', views.edit_firm, name='editfirm'),
	url(r'^nip/(?P<nip>[0-9]+)/$', views.edit_firm, name='editfirm'),
	url(r'^nip/(?P<nip>[0-9]+)/lokacja/$', views.new_lokacja, name='new_lokacja'),
	#url(r'^account/edit/(?P<nip>[0-9]+)/$', views.edit_firm, name='editfirm'),
	url(r'^newfi/$', views.new_firm, name='new_firm'),
	#url(r'^newfi/$', views.new_firm_done, name='new_firm_done'),
	url(r'^nip/$', views.potw_nip, name='potw_nip'),
	url(r'^nip/(?P<nip>[0-9]+)/(?P<nazwa>[-\w]+)/$', views.edit_lokacja, name='editlokacja'),
		
]

market/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^account/', include('account.urls')),
	url(r'^klient/', include('klient.urls', namespace='klient')),
	#url(r'^cart/', include('cart.urls', namespace='cart')),
	#url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^product/', include('product.urls', namespace='product')),
	url(r'^sitepage/', include('sitepage.urls', namespace='sitepage')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

klient/models.py
from django.core.urlresolvers import reverse
from django.db import models
#from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from django.utils.text import slugify
from kontrahent.models import Miejscowosc



class Catkli(models.Model):
	nazwa = models.CharField(max_length=60, default='gotówka')
	slug = models.SlugField(max_length=66, blank=True)

	class Meta:
		ordering = ('nazwa',)
		
	def __str__(self):
		return self.nazwa


class Klient(models.Model):
	RODZFIRM_CHOICES = (('działalność', 'Jednoosobowa działalność gospodarcza'), 
							('spółka cywilna', 'Spółka cywilna'),
							('spółka jawna', 'Spółka jawna'),
							('spółka komandytowa', 'Spółka komandytowa'),
							('spółka zoo', 'Spółka z.o.o'),
							('spółka akcyjna', 'Spółka akcyjna'))
	STATUS_CHOICES = (('aktywny', 'aktywny'), ('ban', 'ban'))
	RODZKLI_CHOICES = (('gotówka', 'gotówka'), ('przelew', 'przelew'))
	nazwa = models.CharField(max_length=30, unique=True, blank=True)
	slug = models.SlugField(max_length=50, blank=True)
	firma = models.CharField(max_length=80)
	miejscowosc = models.ForeignKey(Miejscowosc, related_name='klientos', blank=True)
	adres = models.CharField(max_length=60)
	kodpocztowy = models.CharField(max_length=6)
	rodzfirm = models.CharField(max_length=60, choices=RODZFIRM_CHOICES, default='działalność')
	nip = models.CharField(max_length=10)
	krs = models.CharField(max_length=10, blank=True)
	ceidg = models.CharField(max_length=10, blank=True)
	regon = models.CharField(max_length=9, blank=True)
	shortopis = models.CharField(max_length=200, blank=True)
	opis = models.TextField(blank=True)
	link2 = models.URLField(blank=True)
	status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='aktywny')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	rodzplat = models.CharField(max_length=20, choices=RODZKLI_CHOICES, default='gotówka')

	class Meta:
		ordering = ('nazwa',)
		
	def __str__(self):
		return self.nazwa
		
	#def save(self, *args, **kwargs):
		#if not self.slug:
			#self.slug = slugify(self.nazwa)
			#super(Klient, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('klient:editfirm',
							args=[self.nip])
							
						
class Lokacja(models.Model):
	DZIEN_CHOICES = (('poniedziałek', 'poniedziałek'),
						('wtorek', 'wtorek'),
						('środa', 'środa'),
						('czwartek', 'czwartek'),
						('piątek', 'piątek'))
	klient = models.ForeignKey(Klient, related_name='lokacjas')
	nazwa = models.CharField(max_length=40, unique=True, blank=True)
	slug = models.SlugField(max_length=50, blank=True)
	miejscowosc = models.ForeignKey(Miejscowosc, related_name='lokacjas', default=2)
	adres = models.CharField(max_length=60, blank=True)
	kodpocztowy = models.CharField(max_length=6, blank=True)
	dzienodciecia = models.CharField(max_length=15, blank=True, choices=DZIEN_CHOICES)
	dnidostawy = models.CharField(max_length=25, blank=True)
	godzdostawy = models.CharField(max_length=25, blank=True)
	shortopis = models.CharField(max_length=100, blank=True)
	link1 = models.URLField(blank=True)
	link2 = models.URLField(blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('nazwa',)
		
	def __str__(self):
		return self.nazwa
		
	#def save(self, *args, **kwargs):
		#if not self.slug:
			#self.slug = slugify(self.nazwa)
			#super(Lokacja, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('klient:lokacja',
							args=[self.nazwa])
							
							
							
class Detale(models.Model):
	klient = models.OneToOneField(Klient, related_name='detales')
	rabatz = models.DecimalField(max_digits=4, decimal_places=2, blank=True)
	rabatr = models.DecimalField(max_digits=4, decimal_places=2, blank=True)
	kredytlimit = models.DecimalField(max_digits=8, decimal_places=2, blank=True)
	peyment = models.PositiveIntegerField(blank=True, default=0)
	
	
class Grupa(models.Model):
	nazwa = models.CharField(max_length=40, db_index=True)
	slug = models.SlugField(max_length=50, blank=True)
	
	class Meta:
		ordering = ('nazwa',)
		
	def __str__(self):
		return self.nazwa
		
	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.nazwa)
			super(Grupa, self).save(*args, **kwargs)

klient/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Klient, Lokacja


class KlientEditForm(forms.ModelForm):
	class Meta:
		model = Klient
		fields = ('nazwa', 
					'firma', 
					'miejscowosc', 
					'adres', 
					'kodpocztowy', 
					'rodzfirm', 
					'nip', 
					'krs', 
					'ceidg', 
					'regon', 
					'shortopis', 
					'opis', 
					'link2')
		

class SprFirm(forms.Form):
	nip_firmy = forms.CharField(max_length=10)

	
class LokacjaEditForm(forms.ModelForm):
	class Meta:
		model = Lokacja
		fields = ('nazwa', 
					'miejscowosc', 
					'adres', 
					'kodpocztowy', 
					'dzienodciecia', 
					'dnidostawy', 
					'godzdostawy', 
					'shortopis')
	
	
'''class ImageItemEditForm(forms.ModelForm):
	class Meta:
		model = ImageItem
		fields = ('title', 'image', 'opis')	'''

klient/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import KlientEditForm, SprFirm, LokacjaEditForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Klient, Lokacja
from account.models import Profile
from django.contrib.auth.models import User


@login_required
def potw_nip(request):
		
	return render(request, 'klient/potw_nip.html',)	

@login_required
def firma_sprawdzana(request, nip=None):
	
	if request.method == 'POST':
		spr_form = SprFirm(request.POST)
		if spr_form.is_valid():
			cd = spr_form.cleaned_data
			klient = Klient.objects.filter(nip=cd['nip_firmy'])
			if klient:
				klient = get_object_or_404(Klient, nip=cd['nip_firmy'])
				profile = get_object_or_404(Profile, user=request.user)
				profile.klient = klient
				profile.save()
				
			
				return render(request, 'klient/sprfirma.html', {'klient': klient})
			
			else: 	
				komenda = 'Firma o podanym NIP-ie nie istnieje.'
				return render(request, 'klient/sprfirma.html', {'komenda': komenda})
	else:
		spr_form = SprFirm()
		
	return render(request, 'klient/sprfirma.html', {'spr_form': spr_form})
	
	
	
@login_required
def new_firm(request): 
	
	if request.method == 'POST':
		new_klient_form = KlientEditForm(data=request.POST, files=request.FILES)
        
		if  new_klient_form.is_valid():
			cd = new_klient_form.cleaned_data
			nazwa = cd['nazwa']
			miejscowosc = cd['miejscowosc']
			adres = cd['adres']
			kodpocztowy = cd['kodpocztowy']
			new_klient = new_klient_form.save(commit=False)
			
			profile = get_object_or_404(Profile, user=request.user)
			new_klient.save()			
			profile.klient = new_klient
			lokacja = Lokacja.objects.create(klient=new_klient)
			lokacja.nazwa = nazwa
			lokacja.miejscowosc = miejscowosc
			lokacja.adres = adres
			lokacja.kodpocztowy = kodpocztowy
			
			profile.save()
			lokacja.save()
			klient = new_klient
			
			messages.success(request, 'Uaktualnienie profilu zakończyło się sukcesem.')
			
						
										
			return render(request, 'klient/new_firm_done.html', 						
										{'klient': klient})
		else:
			messages.error(request, 'Wystąpił błąd podczas uaktualniania profilu.')
	else:
		new_klient_form = KlientEditForm()
												
	return render(request,
					'klient/new_firm.html',
						{'new_klient_form': new_klient_form})	


@login_required
def edit_firm(request, nip): 
	
	klient = get_object_or_404(Klient, nip=nip)
	lokacjas = Lokacja.objects.filter(klient=klient)
	
	if request.method == 'POST':
		klient_form = KlientEditForm(instance=klient, data=request.POST, files=request.FILES)
		if klient_form.is_valid():
			cd = klient_form.cleaned_data
			klient = klient_form.save(commit=False)
			
			klient.save()			
			
			
			messages.success(request, 'Uaktualnienie danych firmowych '\
										'zakończyło się sukcesem.')
		else:
			messages.error(request, 'Wystąpił błąd podczas uaktualniania danych firmowych.')
	else:
		klient_form = KlientEditForm(instance=klient)
		lokacjas = Lokacja.objects.filter(klient=klient)
												
	return render(request,
					'klient/editfirm.html',
						{'klient_form': klient_form, 'lokacjas': lokacjas})
						
						
						
@login_required
def new_lokacja(request, nip): 
	
	if request.method == 'POST':
		new_lokacja_form = LokacjaEditForm(data=request.POST, files=request.FILES)
        
		if  new_lokacja_form.is_valid():
			cd = new_lokacja_form.cleaned_data
			new_lokacja = new_lokacja_form.save(commit=False)
			
			klient = get_object_or_404(Klient, nip=nip)
			new_lokacja.klient = klient			
			new_lokacja.save()
			
						
			messages.success(request, 'Uaktualnienie profilu '\
										'zakończyło się sukcesem.')
		else:
			messages.error(request, 'Wystąpił błąd podczas uaktualniania profilu.')
	else:
		new_lokacja_form = LokacjaEditForm()
												
	return render(request,
					'klient/new_lokacja.html', {'new_lokacja_form': new_lokacja_form})

					
					
@login_required
def edit_lokacja(request, nip, nazwa):
	lokacja = get_object_or_404(Lokacja, nazwa=nazwa)
	if request.method == 'POST':
		lokacja_form = LokacjaEditForm(instance=lokacja, data=request.POST, files=request.FILES)
        
		if  lokacja_form.is_valid():
			cd = lokacja_form.cleaned_data
			lokacja = lokacja_form.save(commit=False)
			
			lokacja.save()
			
						
			messages.success(request, 'Uaktualnienie profilu '\
										'zakończyło się sukcesem.')
		else:
			messages.error(request, 'Wystąpił błąd podczas uaktualniania profilu.')
	else:
		lokacja_form = LokacjaEditForm(instance=lokacja)
												
	return render(request,
					'klient/editlokacja.html',
						{'lokacja_form': lokacja_form, 'lokacja': lokacja})	

klient/templates/klient/editfirm.html
{% extends "dopustbase.html" %}

{% block title %}Edycja danych firmowych{% endblock %}

{% block content %}
  <h1 class="acount">Edycja danych firmowych</h1>
 
  
  <p class="acount">Za pomocą poniższego formularza możesz edytować dane firmowe dla wystawienia faktury</p>
  <div class="login-form">
  <form action="." method="post" enctype="multipart/form-data">
    {{ klient_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Zapisz zmiany"></p>
  </form>
   
  </div>
  
  
  <div id="lokacje">
 <p class="acount">Lokalizacje dla dostaw</p>
  {% for l in lokacjas %}
   <h3 class="acount1"><a href="{{ l.nazwa }}">{{ l.nazwa }}</a></h3>
   {% endfor %}
   <br><br><br>
   <p class="acount"><a href="{{ klient.nip }}lokacja">Dodaj nową</a></p>
  </div>
  
  {% endblock %}

klient/templates/klient/editlokacja.html
{% extends "dopustbase.html" %}

{% block title %}Edycja danych firmowych{% endblock %}

{% block content %}
  <h1 class="acount">Edycja danych dla lokalizacji</h1>
  <h2 class="acount">{{ nip }}</h2>
  
  <p class="acount">Za pomocą poniższego formularza możesz edytować dane dla określenia parametrów dostawy dla wybranej lokalizacji:</p>
  <h2 class="acount1">{{ lokacja.nazwa }}</h2>
  <div class="login-form">
  <form action="." method="post" enctype="multipart/form-data">
    {{ lokacja_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Zapisz zmiany"></p>
  </form>
  </div>
  {% endblock %}

klient/templates/klient/new_firm.html
{% extends "dopustbase.html" %}

{% block title %}Edycja danych firmowych{% endblock %}

{% block content %}
  <h1 class="acount">Wprowadzenie danych firmowych</h1>
  
  
  <p class="acount">Za pomocą poniższego formularza możesz edytować dane firmowe dla wystawienia faktury</p>
  <div class="login-form">
  {% if request.user.profile.klient.nip == '0000000001' %}
  <form action="." method="post" enctype="multipart/form-data">
    {{ new_klient_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Zapisz zmiany"></p>
  </form>
  {% else %}
  <p class="acount">{{ request.user.profil.klient.nazwa }}</p>
  <p class="acount">{{ klient.firma }}</p>
  <p class="acount">{{ klient.adres }}</p>
  <p class="acount">{{ klient.kodpocztowy }}</p>
  <p class="acount">{{ klient.miejscowosc }}</p>
  <p class="acount"><a href="{{ klient.nip }}">{{ klient.nip }}</a></p>
  {% endif %}
  </div>
  {% endblock %}

klient/templates/klient/new_firm_done.html
{% extends "dopustbase.html" %}

{% block title %}Edycja danych firmowych{% endblock %}

{% block content %}
  <h1 class="acount">Firma została dodana</h1>
  
  
  <p class="acount">Przejdź do edycji danych firmowych</p>
  <div class="login-form">
  <p class="acount">{{ request.user.profil.klient.nazwa }}</p>
  <p class="acount">{{ klient.firma }}</p>
  <p class="acount">{{ klient.adres }}</p>
  <p class="acount">{{ klient.kodpocztowy }}</p>
  <p class="acount">{{ klient.miejscowosc }}</p>
  <p class="acount">{{ klient.nip }}</p>
  <h2 class="acount"><a href="{% url 'dashboard' %}">OK</a></h2>
  
  </div>
  {% endblock %}

klient/templates/klient/new_lokacja.html
{% extends "dopustbase.html" %}

{% block title %}Edycja danych firmowych{% endblock %}

{% block content %}
  <h1 class="acount">Dodaj nową lokalizację</h1>
  <h2 class="acount">{{ nip }}</h2>
  
  <p class="acount">Za pomocą poniższego formularza możesz dodać nową lokalizacje dla dostawy</p>
  <div class="login-form">
  <form action="." method="post" enctype="multipart/form-data">
    {{ new_lokacja_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Zapisz zmiany"></p>
  </form>
  </div>
  {% endblock %}

klient/templates/klient/potw_nip.html
{% extends "dopustbase.html" %}

{% block title %}Edycja danych firmowych{% endblock %}

{% block content %}
  
  
  <h1 class="acount">Potwierdź NIP: {{ request.user.profile.klient.nip }}</h1>
 
  <div id="pspr1">
	                                  
  
			
			<h2 class="acount"><a href="{{ request.user.profile.klient.nip }}">Potwierdzam</a></h2>
					
  </div>
   
  
 		
{% endblock %}
<

klient/templates/klient/sprfirma.html
{% extends "dopustbase.html" %}

{% block title %}Edycja danych firmowych{% endblock %}

{% block content %}
  
  
  <h1 class="acount">Sprawdź, czy twoja firma jest bazie?</h1>
 
  <div class="login-form">
	<form action="." method="post">
    {{ spr_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Sprwdź"></p>                                  
  </form>
   </div>
  
  <div id="pspr">
			<p class="acount">{{ komenda }}</p>
			{% if  komenda %}
			<h2 class="acount"> <a href="{% url "klient:new_firm" %}">DODAJ FIRMĘ</a></h2>
			{% elif klient %}
			<h3 class="acount"><a href="{{ request.user.profile.klient.nip }}">Dane firmy:</a></h3>
			<p class="acount">Nazwa:&nbsp&nbsp {{ klient.nazwa }}</p>
			<p class="acount">Miejscowość: &nbsp&nbsp{{ klient.miejscowosc }}</p>
			<p class="acount">NIP: &nbsp&nbsp{{ klient.nip }}</p>
			{% else %}
			<p class="acount">Czekamy</p><br>
			{% endif %}
			
 </div>
   
  
 		
{% endblock %}
<