klient/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	
    #url(r'^$', views.realestate_start, name='startre'),
	#url(r'^cennik/$', views.cennik, name='cennik'),
	#url(r'^regulamin/$', views.regulamin, name='regulamin'),
	#url(r'^edfi/$', views.edit_firm, name='editfirm'),
	#url(r'^pitka/$', views.probino, name='probino'),
	url(r'^fspr/$', views.firma_sprawdzana, name='sprfirma'),
	url(r'^fspr/(?P<nip>[0-9]+)/$', views.edit_firm, name='editfirm'),
	url(r'^nip/(?P<nip>[0-9]+)/$', views.edit_firm, name='editfirm'),
	url(r'^nip/(?P<nip>[0-9]+)/lokacja/$', views.new_lokacja, name='new_lokacja'),
	#url(r'^account/edit/(?P<nip>[0-9]+)/$', views.edit_firm, name='editfirm'),
	url(r'^newfi/$', views.new_firm, name='new_firm'),
	#url(r'^newfi/$', views.new_firm_done, name='new_firm_done'),
	url(r'^nip/$', views.potw_nip, name='potw_nip'),
	url(r'^nip/(?P<nip>[0-9]+)/(?P<nazwa>[-\w]+)/$', views.edit_lokacja, name='editlokacja'),
		
]

market/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^account/', include('account.urls')),
	url(r'^klient/', include('klient.urls', namespace='klient')),
	#url(r'^cart/', include('cart.urls', namespace='cart')),
	#url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^product/', include('product.urls', namespace='product')),
	url(r'^sitepage/', include('sitepage.urls', namespace='sitepage')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^product/$', views.prod_list, name='jh_list'),
	url(r'^product/(?P<producent_slug>[-\w]+)/$', views.prod_list_producent, name='jh_list_by_producent'),
	#url(r'^product/(?P<producent_slug>[-\w]+)/$', views.prod_list_producent, name='jh_list_by_producent'),
	url(r'^stomatologia/$', views.prod_list_stomat, name='prod_list_stomat'),
	url(r'^product/(?P<producent_slug>[-\w]+)/stomatologia/$', views.prod_list_stomat_producent, name='prod_list_stomat_by_producent'),
	url(r'^sip/$', views.prod_list_sip, name='prod_list_sip'),
	url(r'^product/(?P<producent_slug>[-\w]+)/sip/$', views.prod_list_sip_producent, name='prod_list_sip_by_producent'),
	url(r'^ds/$', views.prod_list_ds, name='prod_list_ds'),
	url(r'^product/(?P<producent_slug>[-\w]+)/ds/$', views.prod_list_ds_producent, name='prod_list_ds_by_producent'),
	url(r'^sc/$', views.prod_list_sc, name='prod_list_sc'),
	url(r'^product/(?P<producent_slug>[-\w]+)/sc/$', views.prod_list_sc_producent, name='prod_list_sc_by_producent'),
	url(r'^jed/$', views.prod_list_jed, name='prod_list_jed'),
	url(r'^product/(?P<producent_slug>[-\w]+)/jed/$', views.prod_list_jed_producent, name='prod_list_jed_by_producent'),
	url(r'^biuro/$', views.prod_list_biuro, name='prod_list_biuro'),
	url(r'^product/(?P<producent_slug>[-\w]+)/biuro/$', views.prod_list_biuro_producent, name='prod_list_biuro_by_producent'),
	url(r'^(?P<product_slug>[-\w]+)/$', views.prod_detail, name='jh_list_by_product'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
		views.jh_detail,
		name='jh_detail'),
]

product/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse

class Producent(models.Model):
	nazwa = models.CharField(max_length=30, db_index=True)
	slug = models.SlugField(max_length=40, db_index=True, unique=True)
	firma = models.CharField(max_length=100, blank=True)
	kraj = models.CharField(max_length=60, blank=True)
	miasto = models.CharField(max_length=30, blank=True)
	kodpocztowy = models.CharField(max_length=20, blank=True)
	ulica = models.CharField(max_length=40, blank=True)
	numer = models.CharField(max_length=10, blank=True)
	
	
	class Meta:
		ordering = ('nazwa',)


	def __str__(self):
		return self.nazwa
		
	def get_absolute_url(self):
		return reverse('product:jh_list_by_producent',
							args=[self.slug])
	

	
	
class Profilmat(models.Model):
	nazwa = models.CharField(max_length=30)
	slug = models.SlugField(max_length=40, unique=True)	
	

	class Meta:
		ordering = ('nazwa',)


	def __str__(self):
		return self.nazwa
		
		

class Cotojest(models.Model):
	nazwa = models.CharField(max_length=60, unique=True)
	slug = models.SlugField(max_length=70, unique=True)	
	
	class Meta:
		ordering = ('nazwa',)


	def __str__(self):
		return self.nazwa
		
	def get_absolute_url(self):
		return reverse('product:jh_list_by_producent',
							args=[self.slug])
		
class Product(models.Model):
	
	nazwa = models.CharField(max_length=60, db_index=True)
	slug = models.SlugField(max_length=80, db_index=True, unique=True)
	producent = models.ForeignKey(Producent, related_name='products', blank=True)
	cotojest = models.ForeignKey(Cotojest, related_name='productsy')
	kategoria = models.CharField(max_length=60, blank=True)
	shortopis = models.CharField(max_length=100, blank=True)
	opis = models.TextField(blank=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	fotka = models.URLField(blank=True)
	dokprod1 = models.URLField(blank=True)
	dokprod2 = models.URLField(blank=True)
	dokprod3 = models.URLField(blank=True)
	dokprod4 = models.URLField(blank=True)
	pod_vat = models.DecimalField(max_digits=5, decimal_places=2, blank=True)
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	profilmat = models.ForeignKey(Profilmat, related_name='productsy')

	class Meta:
		ordering = ('nazwa',)
		verbose_name = 'product'
		verbose_name_plural = 'products'

	def __str__(self):
		return self.nazwa

	def get_absolute_url(self):
		return reverse('product:jh_list_by_product',
							args=[self.slug])


class Jh(models.Model):
	jh = models.ForeignKey(Product, related_name='jhs')
	name = models.CharField(max_length=80, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	opis1 = models.CharField(max_length=80, blank=True)
	opis2 = models.CharField(max_length=80, blank=True)
	opis3 = models.CharField(max_length=80, blank=True)
	image = models.ImageField(upload_to='jhs/%Y/%m/%d',
							blank=True)
	jm = models.CharField(max_length=8)
	ilop = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
	nrkat = models.CharField(max_length=30, blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
	stock = models.PositiveIntegerField(blank=True)
	rabatmax = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
	zawart = models.CharField(max_length=200, blank=True)
	label = models.CharField(max_length=60, blank=True)
	status = models.CharField(max_length=20, blank=True)
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('product:jh_detail',
						args=[self.id, self.slug])

product/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Product, Producent



class FiltrCotojestForm(forms.ModelForm):
	
	class Meta:
		model = Product
		fields = ('cotojest',)
		

class FiltrRynekForm(forms.Form):
	RYNEK_CHOICES = (('1', 'wtórny'), 
						('2', 'pierwotny'))
	rynek = forms.ChoiceField(choices=RYNEK_CHOICES, label='Rynek')
		

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Jh, Producent, Cotojest
from .forms import FiltrCotojestForm
from django.contrib.auth.decorators import login_required
#from cart.forms import CartAddJhForm



def prod_list(request, product_slug=None):
	product = None
	
	if request.method == 'POST':
	
		filtrcotojest_form = FiltrCotojestForm(request.POST)
		products = Product.objects.all()
		producents = Producent.objects.all()
		jhs = Jh.objects.filter(available=True)
		
		if filtrcotojest_form.is_valid():
			cd = filtrcotojest_form.cleaned_data
			products = products.filter(cotojest=cd['cotojest'])
			
			
	
			return render(request, 'product/product/list.html', {'product': product, 
																	'products': products, 
																	'producents': producents,
																	'filtrcotojest_form': filtrcotojest_form})
	else:
		products = Product.objects.all()
		producents = Producent.objects.all()
		jhs = Jh.objects.filter(available=True)
		filtrcotojest_form = FiltrCotojestForm()
		
		return render(request, 'product/product/list.html', {'product': product, 
																	'products': products, 
																	'producents': producents,
																	'filtrcotojest_form': filtrcotojest_form})
		
		
	
def prod_list_producent(request, producent_slug):
	product = None
	if producent_slug:
		producents = Producent.objects.all()
		producent = get_object_or_404(Producent, slug=producent_slug)
		products = Product.objects.filter(producent=producent)
		if request.method == 'POST':
		
			filtrcotojest_form = FiltrCotojestForm(request.POST)
			if filtrcotojest_form.is_valid():
				cd = filtrcotojest_form.cleaned_data
				products = products.filter(cotojest=cd['cotojest'])
				
	
				return render(request, 'product/product/list.html', {'product': product, 
																		'products': products, 
																		'producent': producent,
																		'producents': producents,
																		'filtrcotojest_form': filtrcotojest_form})
															
															
		else:
			filtrcotojest_form = FiltrCotojestForm()
			producents = Producent.objects.all()
			producent = get_object_or_404(Producent, slug=producent_slug)
			products = Product.objects.filter(producent=producent)
			
		
			return render(request, 'product/product/list.html', {'product': product, 
																	'products': products, 
																	'producent': producent,
																	'producents': producents,
																	'filtrcotojest_form': filtrcotojest_form})														


																	
																	
def prod_list_stomat(request):
	product = None
	products = Product.objects.filter(profilmat=1)
	producents = Producent.objects.all()
	jhs = Jh.objects.filter(available=True)
	if request.method == 'POST':
		filtrcotojest_form = FiltrCotojestForm(request.POST)
		if filtrcotojest_form.is_valid():
			cd = filtrcotojest_form.cleaned_data
			products = products.filter(cotojest=cd['cotojest'])
		
	
			return render(request, 'product/product/listprofil1.html', {'product': product, 
																			'products': products, 
																			'producents': producents,
																			'filtrcotojest_form': filtrcotojest_form})
	else:
		products = Product.objects.filter(profilmat=1)
		producents = Producent.objects.all()
		jhs = Jh.objects.filter(available=True)
		filtrcotojest_form = FiltrCotojestForm()
		
		return render(request, 'product/product/listprofil1.html', {'product': product, 
																	'products': products, 
																	'producents': producents,
																	'filtrcotojest_form': filtrcotojest_form})																
				



				

def prod_list_stomat_producent(request, producent_slug):
	product = None
	products = Product.objects.filter(profilmat=1)
	producents = Producent.objects.all()
	if producent_slug:
		producent = get_object_or_404(Producent, slug=producent_slug)
		products = products.filter(producent=producent)
		jhs = Jh.objects.filter(available=True)
		
		if request.method == 'POST':
			filtrcotojest_form = FiltrCotojestForm(request.POST)
			if filtrcotojest_form.is_valid():
				cd = filtrcotojest_form.cleaned_data
				products = products.filter(cotojest=cd['cotojest'])
				
	
				return render(request, 'product/product/listprofil1.html', {'product': product, 
																				'products': products, 
																				'producent': producent,
																				'producents': producents,
																				'filtrcotojest_form': filtrcotojest_form})
																		
		else:
			filtrcotojest_form = FiltrCotojestForm()
			
			
		
			return render(request, 'product/product/listprofil1.html', {'product': product, 
																			'products': products, 
																			'producent': producent,
																			'producents': producents,
																			'filtrcotojest_form': filtrcotojest_form})																
	
	


def prod_list_sip(request):
	product = None
	products = Product.objects.filter(profilmat=2)
	producents = Producent.objects.all()
	#jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil2.html', {'product': product, 'products': products, 'producents': producents})
	
	
def prod_list_sip_producent(request, producent_slug=None):
	product = None
	products = Product.objects.filter(profilmat=2)
	producents = Producent.objects.all()
	if producent_slug:
		producent = get_object_or_404(Producent, slug=producent_slug)
		products = products.filter(producent=producent)
		
		jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil2.html', {'product': product, 
																	'products': products, 
																	'producents': producents})


def prod_list_jed(request):
	product = None
	products = Product.objects.filter(profilmat=3)
	producents = Producent.objects.all()
	#jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil3.html', {'product': product, 'products': products, 'producents': producents})
	
	
def prod_list_jed_producent(request, producent_slug=None):
	product = None
	products = Product.objects.filter(profilmat=3)
	producents = Producent.objects.all()
	if producent_slug:
		producent = get_object_or_404(Producent, slug=producent_slug)
		products = products.filter(producent=producent)
		
		jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil3.html', {'product': product, 
																	'products': products, 
																	'producents': producents})
	
	
def prod_list_ds(request):
	product = None
	products = Product.objects.filter(profilmat=4)
	producents = Producent.objects.all()
	#jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil4.html', {'product': product, 'products': products, 'producents': producents})
	
	
def prod_list_ds_producent(request, producent_slug=None):
	product = None
	products = Product.objects.filter(profilmat=4)
	producents = Producent.objects.all()
	if producent_slug:
		producent = get_object_or_404(Producent, slug=producent_slug)
		products = products.filter(producent=producent)
		
		jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil4.html', {'product': product, 
																	'products': products, 
																	'producents': producents})
	
	
	
def prod_list_sc(request):
	product = None
	products = Product.objects.filter(profilmat=5)
	producents = Producent.objects.all()
	#jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil5.html', {'product': product, 
																	'products': products,
																	'producents': producents})
	
	
def prod_list_sc_producent(request, producent_slug=None):
	product = None
	products = Product.objects.filter(profilmat=5)
	producents = Producent.objects.all()
	if producent_slug:
		producent = get_object_or_404(Producent, slug=producent_slug)
		products = products.filter(producent=producent)
		
		jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil5.html', {'product': product, 
																	'products': products, 
																	'producents': producents})
	
	
	
def prod_list_biuro(request):
	product = None
	products = Product.objects.filter(profilmat=6)
	producents = Producent.objects.all()
	#jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil6.html', {'product': product, 
																	'products': products,
																	'producents': producents})
	
	
def prod_list_biuro_producent(request, producent_slug=None):
	product = None
	products = Product.objects.filter(profilmat=6)
	producents = Producent.objects.all()
	if producent_slug:
		producent = get_object_or_404(Producent, slug=producent_slug)
		products = products.filter(producent=producent)
		
		jhs = Jh.objects.filter(available=True)
	
	return render(request, 'product/product/listprofil6.html', {'product': product, 
																	'products': products, 
																	'producents': producents})
	

def prod_detail(request, product_slug):
	
	if product_slug:
		product = get_object_or_404(Product, slug=product_slug)
		jhs = Jh.objects.filter(available=True,jh=product)
	#cart_jh_form = CartAddProductForm()
	
	return render(request, 'product/product/list_prod.html', {'product': product, 'jhs': jhs, })


def jh_detail(request, id, slug):
	jh = get_object_or_404(Jh, id=id, slug=slug, available=True)
	#cart_jh_form = CartAddJhForm()
	
	return render(request, 'product/product/detail.html', {'jh': jh})

product/templates/product/product/detail.html
{% extends "product/productbase.html" %}
{% load static %}

{% block title %}
  {% if product %}{{ product.title }}{% else %}Produkt{% endif %}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if jh.image %}{{ jh.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
    <h2>{{ p.nazwa }}{{ jh.label }} {{ jh.name }} {{ jh.opis1 }} {{ jh.opis2 }} {{ jh.opis3 }}</h2>
    <h2><a href="{{ jh.product.get_absolute_url }}">{{ jh.product }}</a></h2>
    <h1 class="price">{{ jh.price }} zł</h1>
	<form action="#" method="post">
		
	<input type="submit" value="Dodaj">
	</form>
	<h3>{{ jh.zawart }}</h3>
  </div>
{% endblock %}

product/templates/product/product/list.html
{% extends "product/productbase.html" %}
{% load static %}

{% block title %}
  {% if product %}{{ product.nazwa }}{% else %}Produkty{% endif %}
{% endblock %}

{% block content %}
    
  <div id="sidebar">
    <h4 {% if not product %}class="selected"{% endif %}>
	<a href="{% url "product:jh_list" %}">Wszystkie</a>
	</h4>
    
	 <table class="cart">
      <h4>{{ producent }}</h4>
	  <tbody>
	  	  
      {% for p in products %}
          <tr>
            <td><a href="{{ p.get_absolute_url }}">{{ p.nazwa }}</a></td>
			<td>{{ p.cotojest }}</td>
			<td>{{ p.producent }}</td>
			
          </tr>
      {% endfor %}
     </tbody>
	 </table>
    </div>
	
	<div id="midleside">
	<h4>Producent</h4>
	
	  	  
      {% for p in producents %}
           <p id="producent"><a href="{{ p.get_absolute_url }}">{{ p.nazwa }}</a></p>
			
          
      {% endfor %}
     
   </div>
	<div id="leftside">
	<h4>Co to jest?</h4>
	
	<form action="." method="post">
	
	<p>{{ filtrcotojest_form.cotojest }}</p>
	<p><input type="submit" value="Filtruj"></p>
	
	{% csrf_token %}<br><br>
		
	</form>
	</div>
  
{% endblock %}

product/templates/product/product/listprofil1.html
{% extends "product/productbase.html" %}
{% load static %}

{% block title %}
  {% if product %}{{ product.nazwa }}{% else %}Stomatologia{% endif %}
{% endblock %}

{% block content %}

<h2 class="menu">Stomatologia</h2>
  <div id="main">
	<div id="profilo">
	<ul>
		<li id="topik">Materiały</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
    <ul>
		<li id="topik">Narzędzia</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	<ul>
		<li id="topik">Znieczulenia i leki</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	<ul>
		<li id="topik">Pasty i płukanki</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	<ul>
		<li id="topik">Pozostałe</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	</div>
   </div>
   
  <div id="sidebar">
    <h4 {% if not product %}class="selected"{% endif %}>
	<a href="{% url "product:jh_list" %}">Wszystkie</a>
	</h4>
    
	 <table class="cart">
	 <h4>{{ producent }}</h4>
      <tbody>
	  
      {% for p in products %}
          <tr>
            <td><a href="{{ p.get_absolute_url }}">{{ p.nazwa }}</a></td>
			<td>{{ p.cotojest }}</td>
			<td>{{ p.producent }}</td>
          </tr>
      {% endfor %}
     </tbody>
	 </table>
    </div>
	
	<div id="midleside">
	<h4>Producent</h4>
	
	  	  
      {% for p in producents %}
           <p><a href="{{ p.get_absolute_url }}stomatologia">{{ p.nazwa }}</a></p>
			
        {% endfor %}
     
   </div>
	<div id="leftside">
	<h4>Co to jest?</h4>
	<form action="." method="post">
	
	<p>{{ filtrcotojest_form.cotojest }}</p>
	<p><input type="submit" value="Filtruj"></p>
	
	{% csrf_token %}<br><br>
		
	</form>
	

	</div>
  
{% endblock %}

product/templates/product/product/listprofil2.html
{% extends "product/productbase.html" %}
{% load static %}

{% block title %}
  {% if product %}{{ product.nazwa }}{% else %}Medyczne{% endif %}
{% endblock %}

{% block content %}

<h2 class="menu">Medyczne</h2>
  <div id="main">
	<span id="profilo">
	<ul>
		<li id="topik">Medycyna</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
    <ul>
		<li id="topik">Odzież </li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	<ul>
		<li id="topik">Opatrunki</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	<ul>
		<li id="topik">Dodatki</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	<ul>
		<li id="topik">Pozostałe</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	</span>
   </div>
   
  <div id="sidebar">
    <h4 {% if not product %}class="selected"{% endif %}>
	<a href="{% url "product:jh_list" %}">Wszystkie</a>
	</h4>
	 <table class="cart">
      <tbody>
      {% for p in products %}
          <tr>
            <td><a href="{{ p.get_absolute_url }}">{{ p.nazwa }}</a></td>
			<td>{{ p.cotojest }}</td>
			<td>{{ p.producent }}</td>
          </tr>
      {% endfor %}
     </tbody>
	 </table>
    </div>
	<div id="midleside">
	<h4>Producent</h4>
	{% for p in producents %}
           <p><a href="{{ p.get_absolute_url }}sip">{{ p.nazwa }}</a></p>
			
        {% endfor %}
   </div>
	<div id="leftside">
	<h4>Co to jest?</h4>
	<form action="." method="post">
	
	<p>{{ filtrcotojest_form.cotojest }}</p>
	<p><input type="submit" value="Filtruj"></p>
	
	{% csrf_token %}<br><br>
		
	</form>

	</div>
  
{% endblock %}

product/templates/product/product/listprofil3.html
{% extends "product/productbase.html" %}
{% load static %}

{% block title %}
  {% if product %}{{ product.nazwa }}{% else %}Jednorazówka{% endif %}
{% endblock %}

{% block content %}
<h2 class="menu">Jednorazówka</h2>
  <div id="main">
	<span id="profilo">
	<ul>
		<li id="topik">Dezynfekcja</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
    <ul>
		<li id="topik">Sterylizacja </li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	<ul>
		<li id="topik">Środki czystości</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	<ul>
		<li id="topik">Opatrunki</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	<ul>
		<li id="topik">Pozostałe</li>
		<li>Fajowe</li>
		<li>Super gutes</li>
		<li>Takie sobie</li>
	</ul>
	</span>
   </div>
   
  <div id="sidebar">
    <h4 {% if not product %}class="selected"{% endif %}>
	<a href="{% url "product:jh_list" %}">Wszystkie</a>
	</h4>
	 <table class="cart">
      <tbody>
      {% for p in products %}
          <tr>
            <td><a href="{{ p.get_absolute_url }}">{{ p.nazwa }}</a></td>
			<td>{{ p.cotojest }}</td>
			<td>{{ p.producent }}</td>
          </tr>
      {% endfor %}
     </tbody>
	 </table>
    </div>
	<div id="midleside">
	<h4>Producent</h4>
	{% for p in producents %}
           <p><a href="{{ p.get_absolute_url }}jed">{{ p.nazwa }}</a></p>
			
        {% endfor %}
   </div>
	<div id="leftside">
	<h4>Co to jest?</h4>
	<form action="." method="post">
	
	<p>{{ filtrcotojest_form.cotojest }}</p>
	<p><input type="submit" value="Filtruj"></p>
	
	{% csrf_token %}<br><br>
		
	</form>

	</div>
  
{% endblock %}

product/templates/product/product/show.html
{% extends "platma/platmabase.html" %}
{% load static %}

{% block title %}
  {% if product %}{{ product.nazwa }}{% else %}Start{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Bloki</h3>
    <ul>
      <li>
        <a href="{% url "platma:jh_list" %}">Produkty</a>
      </li>
      </ul>
  </div>
  <div id="main" class="product-list">
    
	
   </div>
    
  </div>
{% endblock %}